/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'Home': RouteRecordInfo<'Home', '/', Record<never, never>, Record<never, never>>,
    '404': RouteRecordInfo<'404', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    'charts': RouteRecordInfo<'charts', '/charts', Record<never, never>, Record<never, never>>,
    '/company/[id]/tasks/': RouteRecordInfo<'/company/[id]/tasks/', '/company/:id/tasks', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'Contract': RouteRecordInfo<'Contract', '/contract', Record<never, never>, Record<never, never>>,
    'ContractId': RouteRecordInfo<'ContractId', '/contract/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/contract/progress': RouteRecordInfo<'/contract/progress', '/contract/progress', Record<never, never>, Record<never, never>>,
    'counter': RouteRecordInfo<'counter', '/counter', Record<never, never>, Record<never, never>>,
    '/feedback/': RouteRecordInfo<'/feedback/', '/feedback', Record<never, never>, Record<never, never>>,
    'KeepAlive': RouteRecordInfo<'KeepAlive', '/keepalive', Record<never, never>, Record<never, never>>,
    'Login': RouteRecordInfo<'Login', '/login', Record<never, never>, Record<never, never>>,
    '/login/privacy-policy': RouteRecordInfo<'/login/privacy-policy', '/login/privacy-policy', Record<never, never>, Record<never, never>>,
    '/login/service-agree': RouteRecordInfo<'/login/service-agree', '/login/service-agree', Record<never, never>, Record<never, never>>,
    'Message': RouteRecordInfo<'Message', '/message', Record<never, never>, Record<never, never>>,
    'MessageChatId': RouteRecordInfo<'MessageChatId', '/message/chat/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'MessageSystem': RouteRecordInfo<'MessageSystem', '/message/system', Record<never, never>, Record<never, never>>,
    'MessageSystemId': RouteRecordInfo<'MessageSystemId', '/message/system/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'mock': RouteRecordInfo<'mock', '/mock', Record<never, never>, Record<never, never>>,
    'My': RouteRecordInfo<'My', '/my', Record<never, never>, Record<never, never>>,
    'MyAccount': RouteRecordInfo<'MyAccount', '/my/account', Record<never, never>, Record<never, never>>,
    'MyAccountCoinExplain': RouteRecordInfo<'MyAccountCoinExplain', '/my/account/coin-explain', Record<never, never>, Record<never, never>>,
    'MyAccountDepositExplain': RouteRecordInfo<'MyAccountDepositExplain', '/my/account/deposit-explain', Record<never, never>, Record<never, never>>,
    'MyAccountPrivacy': RouteRecordInfo<'MyAccountPrivacy', '/my/account/privacy', Record<never, never>, Record<never, never>>,
    'MyAccountWithdrawDeposit': RouteRecordInfo<'MyAccountWithdrawDeposit', '/my/account/withdraw-deposit', Record<never, never>, Record<never, never>>,
    'MyAuthReal': RouteRecordInfo<'MyAuthReal', '/my/auth-real', Record<never, never>, Record<never, never>>,
    'MyCollection': RouteRecordInfo<'MyCollection', '/my/collection', Record<never, never>, Record<never, never>>,
    'MyProfile': RouteRecordInfo<'MyProfile', '/my/profile', Record<never, never>, Record<never, never>>,
    'MyResume': RouteRecordInfo<'MyResume', '/my/resume', Record<never, never>, Record<never, never>>,
    'MyResumePreview': RouteRecordInfo<'MyResumePreview', '/my/resume/preview', Record<never, never>, Record<never, never>>,
    'MySettings': RouteRecordInfo<'MySettings', '/my/settings', Record<never, never>, Record<never, never>>,
    'MySwitchRole': RouteRecordInfo<'MySwitchRole', '/my/switch-role', Record<never, never>, Record<never, never>>,
    '/my/user/auth-real': RouteRecordInfo<'/my/user/auth-real', '/my/user/auth-real', Record<never, never>, Record<never, never>>,
    '/my/user/certified': RouteRecordInfo<'/my/user/certified', '/my/user/certified', Record<never, never>, Record<never, never>>,
    '/my/user/indentity-switch': RouteRecordInfo<'/my/user/indentity-switch', '/my/user/indentity-switch', Record<never, never>, Record<never, never>>,
    '/set/': RouteRecordInfo<'/set/', '/set', Record<never, never>, Record<never, never>>,
    '/talent/': RouteRecordInfo<'/talent/', '/talent', Record<never, never>, Record<never, never>>,
    '/talent/details': RouteRecordInfo<'/talent/details', '/talent/details', Record<never, never>, Record<never, never>>,
    'Task': RouteRecordInfo<'Task', '/task', Record<never, never>, Record<never, never>>,
    'TaskId': RouteRecordInfo<'TaskId', '/task/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'TaskCity': RouteRecordInfo<'TaskCity', '/task/city', Record<never, never>, Record<never, never>>,
    'TaskFilter': RouteRecordInfo<'TaskFilter', '/task/filter', Record<never, never>, Record<never, never>>,
    'TaskPositionType': RouteRecordInfo<'TaskPositionType', '/task/position-type', Record<never, never>, Record<never, never>>,
    'TaskSearch': RouteRecordInfo<'TaskSearch', '/task/search', Record<never, never>, Record<never, never>>,
    'unocss': RouteRecordInfo<'unocss', '/unocss', Record<never, never>, Record<never, never>>,
  }
}
