/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'home': RouteRecordInfo<'home', '/', Record<never, never>, Record<never, never>>,
    '404': RouteRecordInfo<'404', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/accoount/': RouteRecordInfo<'/accoount/', '/accoount', Record<never, never>, Record<never, never>>,
    '/accoount/advance': RouteRecordInfo<'/accoount/advance', '/accoount/advance', Record<never, never>, Record<never, never>>,
    '/accoount/coin-explain': RouteRecordInfo<'/accoount/coin-explain', '/accoount/coin-explain', Record<never, never>, Record<never, never>>,
    '/accoount/deposit-explain': RouteRecordInfo<'/accoount/deposit-explain', '/accoount/deposit-explain', Record<never, never>, Record<never, never>>,
    'charts': RouteRecordInfo<'charts', '/charts', Record<never, never>, Record<never, never>>,
    '/collect/': RouteRecordInfo<'/collect/', '/collect', Record<never, never>, Record<never, never>>,
    'contract': RouteRecordInfo<'contract', '/contract', Record<never, never>, Record<never, never>>,
    '/contract/details': RouteRecordInfo<'/contract/details', '/contract/details', Record<never, never>, Record<never, never>>,
    '/contract/progress': RouteRecordInfo<'/contract/progress', '/contract/progress', Record<never, never>, Record<never, never>>,
    'counter': RouteRecordInfo<'counter', '/counter', Record<never, never>, Record<never, never>>,
    '/feedback/': RouteRecordInfo<'/feedback/', '/feedback', Record<never, never>, Record<never, never>>,
    'KeepAlive': RouteRecordInfo<'KeepAlive', '/keepalive', Record<never, never>, Record<never, never>>,
    '/login/': RouteRecordInfo<'/login/', '/login', Record<never, never>, Record<never, never>>,
    '/login/privacy-policy': RouteRecordInfo<'/login/privacy-policy', '/login/privacy-policy', Record<never, never>, Record<never, never>>,
    '/login/service-agree': RouteRecordInfo<'/login/service-agree', '/login/service-agree', Record<never, never>, Record<never, never>>,
    '/message/': RouteRecordInfo<'/message/', '/message', Record<never, never>, Record<never, never>>,
    '/message/system-details': RouteRecordInfo<'/message/system-details', '/message/system-details', Record<never, never>, Record<never, never>>,
    '/message/system-list': RouteRecordInfo<'/message/system-list', '/message/system-list', Record<never, never>, Record<never, never>>,
    '/message/talk': RouteRecordInfo<'/message/talk', '/message/talk', Record<never, never>, Record<never, never>>,
    'mock': RouteRecordInfo<'mock', '/mock', Record<never, never>, Record<never, never>>,
    'my': RouteRecordInfo<'my', '/my', Record<never, never>, Record<never, never>>,
    '/my/user/': RouteRecordInfo<'/my/user/', '/my/user', Record<never, never>, Record<never, never>>,
    '/my/user/auth-real': RouteRecordInfo<'/my/user/auth-real', '/my/user/auth-real', Record<never, never>, Record<never, never>>,
    '/my/user/certified': RouteRecordInfo<'/my/user/certified', '/my/user/certified', Record<never, never>, Record<never, never>>,
    '/my/user/indentity-switch': RouteRecordInfo<'/my/user/indentity-switch', '/my/user/indentity-switch', Record<never, never>, Record<never, never>>,
    'profile': RouteRecordInfo<'profile', '/profile', Record<never, never>, Record<never, never>>,
    '/resume/': RouteRecordInfo<'/resume/', '/resume', Record<never, never>, Record<never, never>>,
    '/resume/preview': RouteRecordInfo<'/resume/preview', '/resume/preview', Record<never, never>, Record<never, never>>,
    '/set/': RouteRecordInfo<'/set/', '/set', Record<never, never>, Record<never, never>>,
    '/talent/': RouteRecordInfo<'/talent/', '/talent', Record<never, never>, Record<never, never>>,
    '/talent/details': RouteRecordInfo<'/talent/details', '/talent/details', Record<never, never>, Record<never, never>>,
    '/task/': RouteRecordInfo<'/task/', '/task', Record<never, never>, Record<never, never>>,
    '/task/company-source': RouteRecordInfo<'/task/company-source', '/task/company-source', Record<never, never>, Record<never, never>>,
    '/task/details': RouteRecordInfo<'/task/details', '/task/details', Record<never, never>, Record<never, never>>,
    '/task/search': RouteRecordInfo<'/task/search', '/task/search', Record<never, never>, Record<never, never>>,
    'unocss': RouteRecordInfo<'unocss', '/unocss', Record<never, never>, Record<never, never>>,
  }
}
